[package]
name = "pbcurve"
version = "0.1.0"
edition = "2021"
description = "General purpose bonding curve library for pizza.fun"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
uint = "0.9"
