[package]
name = "pbcurve"
version = "0.1.1"
edition = "2021"
description = "General purpose bonding curve library for pizza.fun"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
uint = "0.10.0"
